# Generated by Django 5.0.6 on 2024-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_walk_dogphoto_walkuserdog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
    ]
